spring.application.name=accenture

#Conexão com o banco
spring.datasource.url=jdbc:postgresql://localhost:5432/accenture
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASS}

# JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# Swagger
springdoc.swagger-ui.path=/swagger-ui.html

# Microsoft Entra - OAuth2
spring.security.oauth2.client.registration.azure.client-id=${AZURE_CLIENT_ID}
spring.security.oauth2.client.registration.azure.client-secret=${AZURE_CLIENT_SECRET}
spring.security.oauth2.client.registration.azure.scope=openid,profile,email

spring.security.oauth2.client.provider.azure.issuer-uri=https://login.microsoftonline.com/${AZURE_TENANT_ID}/v2.0
